'use strict';

/**
 * Keyword Ideas Generator — 100% client-side permutation tool.
 *
 * IMPORTANT (read this before touching the group definitions):
 * This tool does NOT call any API and does NOT know real search volume,
 * competition, or ranking data. It mechanically combines a seed keyword
 * with common question words, prepositions and modifier patterns — the
 * same basic "permutation" technique several well-known free keyword
 * tools use for their free tier. Every phrase below is generated by
 * simple string templates, nothing more.
 */

const ALPHABET = 'abcdefghijklmnopqrstuvwxyz'.split('');

/**
 * Each group: { key, title, sub, collapsedByDefault, build(seed) -> string[] }
 * build() returns the list of generated phrases for that group.
 */
const GROUPS = [
  {
    key: 'questions',
    title: 'Questions',
    sub: 'who / what / why / how / when / where / which / can / does / will',
    collapsedByDefault: false,
    build(seed) {
      return [
        `who uses ${seed}`,
        `what is ${seed}`,
        `why ${seed} matters`,
        `how ${seed} works`,
        `when to use ${seed}`,
        `where to find ${seed}`,
        `which ${seed} is best`,
        `can ${seed} help`,
        `does ${seed} work`,
        `will ${seed} help me`,
      ];
    },
  },
  {
    key: 'prepositions',
    title: 'Prepositions',
    sub: 'for / with / without / near / vs / like / to',
    collapsedByDefault: false,
    build(seed) {
      return [
        `${seed} for beginners`,
        `${seed} with examples`,
        `${seed} without experience`,
        `${seed} near me`,
        `${seed} vs traditional methods`,
        `${seed} like a pro`,
        `${seed} to get started`,
      ];
    },
  },
  {
    key: 'comparisons',
    title: 'Comparisons / Commercial',
    sub: 'best / top / alternative / cheap / free / premium / review',
    collapsedByDefault: false,
    build(seed) {
      return [
        `best ${seed}`,
        `top ${seed}`,
        `${seed} alternative`,
        `cheap ${seed}`,
        `free ${seed}`,
        `premium ${seed}`,
        `${seed} review`,
      ];
    },
  },
  {
    key: 'transactional',
    title: 'Transactional',
    sub: 'buy / order / download / get / hire',
    collapsedByDefault: false,
    build(seed) {
      return [
        `buy ${seed}`,
        `order ${seed}`,
        `download ${seed}`,
        `get ${seed}`,
        `hire ${seed} expert`,
      ];
    },
  },
  {
    key: 'informational',
    title: 'Informational',
    sub: 'guide / tutorial / tips / examples / checklist / template',
    collapsedByDefault: false,
    build(seed) {
      return [
        `${seed} guide`,
        `${seed} tutorial`,
        `${seed} tips`,
        `${seed} examples`,
        `${seed} checklist`,
        `${seed} template`,
      ];
    },
  },
  {
    key: 'az',
    title: 'A-Z Autosuggest Style',
    sub: 'seed + each letter a–z, the same pattern autosuggest-style free tools use for long-tail variations',
    collapsedByDefault: true,
    build(seed) {
      return ALPHABET.map((letter) => `${seed} ${letter}`);
    },
  },
];

const els = {
  seedInput: document.getElementById('seedInput'),
  generateBtn: document.getElementById('generateBtn'),
  resultsWrap: document.getElementById('resultsWrap'),
  resultsCount: document.getElementById('resultsCount'),
  copyAllBtn: document.getElementById('copyAllBtn'),
  groupsContainer: document.getElementById('groupsContainer'),
  emptyState: document.getElementById('emptyState'),
};

let lastGenerated = []; // [{ title, terms: string[] }]

function cleanSeed(raw) {
  return (raw || '').trim().replace(/\s+/g, ' ').toLowerCase();
}

function groupToText(group) {
  return `${group.title}:\n${group.terms.join('\n')}`;
}

function buildAllText(groups) {
  return groups.map(groupToText).join('\n\n');
}

function renderGroups(seed) {
  lastGenerated = GROUPS.map((g) => ({
    key: g.key,
    title: g.title,
    sub: g.sub,
    terms: g.build(seed),
  }));

  els.groupsContainer.innerHTML = '';

  lastGenerated.forEach((group, idx) => {
    const def = GROUPS[idx];
    const details = document.createElement('details');
    details.className = 'keyword-group';
    if (!def.collapsedByDefault) details.open = true;

    const summary = document.createElement('summary');
    summary.innerHTML = `
      <span class="kg-heading">
        <span class="kg-title">${escapeHtml(group.title)}</span>
        <span class="kg-sub">${escapeHtml(group.sub)}</span>
        <span class="kg-count">${group.terms.length}</span>
      </span>
      <span class="kg-caret">▸</span>
    `;
    details.appendChild(summary);

    const body = document.createElement('div');
    body.className = 'kg-body';

    const actions = document.createElement('div');
    actions.className = 'kg-actions';
    const copyGroupBtn = document.createElement('button');
    copyGroupBtn.className = 'btn-copy-group';
    copyGroupBtn.type = 'button';
    copyGroupBtn.textContent = 'Copy this group';
    copyGroupBtn.addEventListener('click', () => {
      copyToClipboard(group.terms.join('\n'), `${group.title} copied`);
    });
    actions.appendChild(copyGroupBtn);
    body.appendChild(actions);

    const list = document.createElement('ul');
    list.className = 'kg-list';
    group.terms.forEach((term) => {
      const li = document.createElement('li');
      li.tabIndex = 0;
      li.setAttribute('role', 'button');
      li.setAttribute('aria-label', `Copy "${term}"`);
      li.innerHTML = `<span class="kg-term"></span><span class="kg-copy-icon">copy</span>`;
      li.querySelector('.kg-term').textContent = term;
      const copyThis = () => copyToClipboard(term, 'Idea copied');
      li.addEventListener('click', copyThis);
      li.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); copyThis(); }
      });
      list.appendChild(li);
    });
    body.appendChild(list);

    details.appendChild(body);
    els.groupsContainer.appendChild(details);
  });

  const total = lastGenerated.reduce((sum, g) => sum + g.terms.length, 0);
  els.resultsCount.textContent = `${total} keyword ideas across ${lastGenerated.length} groups`;
  els.resultsWrap.hidden = false;
  els.emptyState.hidden = true;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function generate() {
  const seed = cleanSeed(els.seedInput.value);
  if (!seed) {
    showToast('Enter a seed keyword first');
    els.seedInput.focus();
    return;
  }
  renderGroups(seed);
}

els.generateBtn.addEventListener('click', generate);
els.seedInput.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') { e.preventDefault(); generate(); }
});

els.copyAllBtn.addEventListener('click', () => {
  if (!lastGenerated.length) { showToast('Nothing to copy yet'); return; }
  copyToClipboard(buildAllText(lastGenerated), 'All keyword ideas copied');
});

document.addEventListener('DOMContentLoaded', () => {
  if (typeof renderAffiliateBox === 'function') renderAffiliateBox('seo');
});
